providers:
  - noaa:
      enabled: true
      to-json: false
      grid: "0.25"
      #grid: "1.00"
      #init: 2021-12-22T18:00:00Z
      jsons:
        dir: data/noaa/jsons
  - meteofrance:
      enabled: false
      token: ""
